# Laboratorio 2
## Microestructuras y Sistemas de Trading
### Valentina Escobar y Pablo Mendoza

El presente laboratorio tiene como objetivo analizar el comportamiento de un ETF de acuerdo a la conformación de este y al movimiento de los precios que se presentaron entre el 31 de marzo del 2017 hasta el 29 de marzo del 2018 con el fin de identificar que tan conveniente es para un inversionista rebalancear diariamente durante un año comprando $n$ acciones cuando el rendimiento diario sea de -1%. Se contrastará el capital inicial con el capital final deshaciendo todas las pocisiones del portafolo el 1 de Marzo de 2018. Se realizan diferentes medidas de desempeño que permitan comparar los portafolios resultantes.

## Librerías y Funciones

In [1]:
# Librerias
import quandl
import datetime
import numpy as np
import pandas as pd
import scipy.stats as stats

In [2]:
quandl.ApiConfig.api_key = "My9ygJsz7yTDx_9jcneH" # Quandl API key
fechas = list(['2017-03-31','2018-03-29'])

In [3]:
data_csv = pd.read_csv('/Users/pablomendoza/Documents/ITESO/Trading/Lab_1/Trading/Data/IJH_holdings-1.csv', skiprows = [0,1,2,3,4,5,6,7,8,9], index_col = ['Ticker'])
tick = list(data_csv.index)
weights = data_csv['Weight (%)']
#del data_csv
def Download_QuandL(fechas:'Dates_list ', tick:'Tickers of Stock'):
    dates = { 'gte': fechas[0], 'lte': fechas[1] }
    column = { 'columns': ['date', 'Open', 'Close']}
    data = quandl.get_table('WIKI/PRICES', qopts = column, ticker = tick, date = dates, paginate=True)# ticker = 'WIKI/AAPL' #'AAPL.US'
    data = data.iloc[::-1]
    return data

In [40]:
def Clean_Dicc(dic:'Diccionario a limpiar',sizes:'Tamaño deseado del DF', tick:'Ticker'):
    for h in dic:
        if len(dic[h]) < sizes:
            del dic[h]
        else:
            pass
    return dic

In [5]:
def All_Data(fechas:'Dates_list ', tick:'Ticker'):
    d = {} # Crea un Diccionario Vacío
    for i in range(len(tick)): # ciclo que descarga los datos de Quandl y los guarda como DataFrames en un Diccionario
        nom = str(tick[i])
        d["_{0}".format(nom)] = Download_QuandL(fechas, tick[i])
    return d

In [6]:
def Shares(d:'Data Frame',Capital_Inicial:'Capital Inicial'):
    shares = pd.DataFrame(np.floor((d3['Data_1']['Weight']*Capital_Inicial)/d3['Data_1']['Start']), columns = ['Shares'])
    d = d.join(shares)
    return d

In [7]:
Data = All_Data(fechas, tick)

In [8]:
def Rebalanceo(df, Com, Cap_I, R_R, n_a, we):
    """
    Esta funcion hace los rebalanceos de cada activo de forma diaria por una año
    :param df: DataFrame del Activo
    :param Com: Comisión
    :param Cap_I: Capital Inicial
    :param R_R: Rendimiento de Rebalanceo
    :param n_a: Acciones que se compran al rebalancear
    :param we: 
    :return: 
    """
    a = (df['close']/df['open'])-1
    P_se = df['close']-df['open']
    add_s = list()
    Opp = list()
    comi = list()
    In_shares = np.floor((we*Cap_I)/df['close'][0])
    for i in range(len(df)):
        if a.iloc[i] < R_R:
            add_s.append(n_a)
            Opp.append('Compra')
            comi.append(Com*df['close'].iloc[i]*n_a)
        else:
            add_s.append(0)
            Opp.append('-')
            comi.append(0)
    df = df.join(pd.DataFrame(add_s, columns = ['# Added Shares']))
    df = df.join(pd.DataFrame(Opp, columns = ['Operacion']))
    df = df.join(pd.DataFrame(comi, columns = ['Comisión']))
    df = df.join(pd.DataFrame(P_se, columns = ['Precio de Señal %']))
    Tot_Acciones = pd.DataFrame(list(df['# Added Shares'].cumsum()), columns = ['Shares'])+In_shares
    df = df.join(Tot_Acciones)
    df.head()
    return df

In [65]:
tick = list(d_full.keys())
d_full = Clean_Dicc(Data,248,tick)
d2 = {}
for j in range(len(tick)):
    tabla = Rebalanceo(d_full[tick[j]],0.0003,1000000,-0.01,10,weights[j])
    d2["Data{0}".format(j)] = tabla

In [73]:
d2['Data324']

,date,open,close,# Added Shares,Operacion,Comisión,Precio de Señal %,Shares
None,,,,,,,,
247,2017-03-31,36.95,37.35,0,-,0.00000,0.40,4872.0
246,2017-04-03,37.40,37.50,0,-,0.00000,0.10,4872.0
245,2017-04-04,37.45,37.20,10,Compra,0.08625,-0.25,4872.0
244,2017-04-05,37.30,36.85,10,Compra,0.08805,-0.45,4872.0
243,2017-04-06,36.90,37.15,0,-,0.00000,0.25,4862.0
242,2017-04-07,37.05,37.40,0,-,0.00000,0.35,4862.0
241,2017-04-10,37.45,37.55,0,-,0.00000,0.10,4862.0
240,2017-04-11,37.40,37.90,10,Compra,0.09075,0.50,4862.0
239,2017-04-12,38.00,37.95,0,-,0.00000,-0.05,4862.0
238,2017-04-13,37.85,37.35,0,-,0.00000,-0.50,4862.0
237,2017-04-17,37.60,37.75,10,Compra,0.09330,0.15,4852.0
236,2017-04-18,37.60,37.95,0,-,0.00000,0.35,4852.0
235,2017-04-19,37.90,37.65,0,-,0.00000,-0.25,4852.0
234,2017-04-20,37.95,37.85,10,Compra,0.09330,-0.10,4852.0
233,2017-04-21,37.85,37.75,10,Compra,0.09495,-0.10,4852.0
232,2017-04-24,38.15,37.95,0,-,0.00000,-0.20,4852.0
231,2017-04-25,37.95,38.50,10,Compra,0.09645,0.55,4852.0
230,2017-04-26,38.40,38.90,0,-,0.00000,0.50,4852.0
229,2017-04-27,38.90,38.05,0,-,0.00000,-0.85,4852.0
228,2017-04-28,38.00,37.35,10,Compra,0.10020,-0.65,4842.0
227,2017-05-01,37.50,37.55,10,Compra,0.10140,0.05,4832.0
226,2017-05-02,37.55,37.85,0,-,0.00000,0.30,4832.0
225,2017-05-03,37.75,36.35,0,-,0.00000,-1.40,4832.0
224,2017-05-04,36.35,36.10,0,-,0.00000,-0.25,4822.0
223,2017-05-05,36.30,36.55,10,Compra,0.10185,0.25,4822.0
222,2017-05-08,36.40,36.85,10,Compra,0.10290,0.45,4822.0
221,2017-05-09,36.80,36.15,0,-,0.00000,-0.65,4822.0
220,2017-05-10,36.20,36.55,0,-,0.00000,0.35,4812.0
219,2017-05-11,36.40,36.30,0,-,0.00000,-0.10,4812.0
218,2017-05-12,36.20,36.20,0,-,0.00000,0.00,4812.0
...,...,...,...,...,...,...,...,...
29,2018-02-13,34.20,34.25,0,-,0.00000,0.05,4592.0
28,2018-02-14,34.00,34.35,0,-,0.00000,0.35,4592.0
27,2018-02-15,34.55,34.80,0,-,0.00000,0.25,4592.0
26,2018-02-16,34.75,34.85,10,Compra,0.10845,0.10,4592.0
25,2018-02-20,34.70,34.30,0,-,0.00000,-0.40,4592.0
24,2018-02-21,34.30,33.95,0,-,0.00000,-0.35,4582.0
23,2018-02-22,34.00,34.10,0,-,0.00000,0.10,4572.0
22,2018-02-23,34.10,34.25,10,Compra,0.10905,0.15,4572.0
21,2018-02-26,34.35,34.30,0,-,0.00000,-0.05,4572.0
20,2018-02-27,34.30,33.80,0,-,0.00000,-0.50,4572.0
19,2018-02-28,33.90,33.40,10,Compra,0.11205,-0.50,4562.0
18,2018-03-01,33.30,33.40,10,Compra,0.11415,0.10,4552.0
17,2018-03-02,33.20,33.85,0,-,0.00000,0.65,4552.0
16,2018-03-05,32.75,32.15,0,-,0.00000,-0.60,4552.0
15,2018-03-06,32.25,32.35,0,-,0.00000,0.10,4542.0
14,2018-03-07,32.10,31.65,0,-,0.00000,-0.45,4542.0
13,2018-03-08,31.70,31.10,0,-,0.00000,-0.60,4532.0
12,2018-03-09,31.20,31.60,0,-,0.00000,0.40,4522.0
11,2018-03-12,31.55,32.05,0,-,0.00000,0.50,4522.0
10,2018-03-13,32.05,31.10,0,-,0.00000,-0.95,4522.0
9,2018-03-14,31.20,31.05,10,Compra,0.11205,-0.15,4512.0
8,2018-03-15,31.05,30.80,0,-,0.00000,-0.25,4512.0
7,2018-03-16,30.75,30.25,0,-,0.00000,-0.50,4512.0
6,2018-03-19,30.15,30.15,0,-,0.00000,0.00,4502.0
5,2018-03-20,30.15,30.00,0,-,0.00000,-0.15,4502.0
4,2018-03-21,29.95,30.00,0,-,0.00000,0.05,4502.0
3,2018-03-22,29.85,29.35,10,Compra,0.11055,-0.50,4502.0
2,2018-03-23,29.30,28.75,0,-,0.00000,-0.55,4492.0
1,2018-03-26,28.90,28.90,0,-,0.00000,0.00,4482.0
0,2018-03-27,29.00,29.00,0,-,0.00000,0.00,4482.0

In [ ]:
'HolA'